name: SimpleTags
version: '${project.version}'
main: me.refracdevelopment.simpletags.SimpleTags
authors:
  - Refrac
api-version: "1.13"
softdepend:
  - NBTAPI
  - PlaceholderAPI
  - Skulls
  - HeadDatabase
description: SimpleTags is a plugin that allows you to use custom tags in chat.
website: https://discord.gg/EFeSKPg739
folia-supported: true